Mesd\FileDocumentBundle\Entity\Document:
    type:            entity
    table:           filedocument_document
    repositoryClass: Mesd\FileDocumentBundle\Entity\DocumentRepository
    id:
        id:
            type:     integer
            id:       true
            nullable: false
            generator:
                strategy: AUTO
            sequenceGenerator:
                sequenceName:   filedocument_document_id_seq
                initialValue:   1
                allocationSize: 1
    fields:
        path:
            column:   path
            type:     string
            length:   255
            nullable: false
            unique:   false
        filename:
            column:   filename
            type:     string
            length:   255
            nullable: false
            unique:   false
        mimetype:
            column:   mimetype
            type:     string
            length:   255
            nullable: true
            unique:   false
        category:
            column:   category
            type:     string
            length:   255
            nullable: true
            unique:   false
        hash:
            column:   hash
            type:     string
            length:   255
            nullable: false
            unique:   true
    lifecycleCallbacks:
        prePersist:  [ preUpload ]
        preUpdate:   [ preUpload ]
        postPersist: [ upload ]
        postUpdate:  [ upload ]
        preRemove:   [ storeFilenameForRemove ]
        postRemove:  [ removeDocument ]
