parameters:
    mesd_filedocument_document.class: Mesd\FileDocumentBundle\Entity\Document

services:
    document:
        class:     %mesd_filedocument_document.class%
        arguments: ["%kernel.root_dir%/../", "%dirs%"]