MesdFileDocument_upload:
    path:  /upload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:upload' }

MesdFileDocument_receiveUpload:
    path:  /receiveUpload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:receiveUpload' }
    requirements: { methods: post }

MesdFileDocument_download:
    path:  /{id}/download
    defaults: { _controller: 'MesdFileDocumentBundle:Document:download' }
    requirements:
        id: \d+

document_upload:
    path:  /upload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:upload' }

document_receiveUpload:
    path:  /receiveUpload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:receiveUpload' }
    requirements: { methods: post }

document_download:
    path:  /{id}/download
    defaults: { _controller: 'MesdFileDocumentBundle:Document:download' }
    requirements:
        id: \d+