MesdFileDocument_upload:
    pattern:  /upload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:upload' }

MesdFileDocument_receiveUpload:
    pattern:  /receiveUpload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:receiveUpload' }
    requirements: { _method: post }

MesdFileDocument_download:
    pattern:  /{id}/download
    defaults: { _controller: 'MesdFileDocumentBundle:Document:download' }
    requirements:
        id: \d+

document_upload:
    pattern:  /upload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:upload' }

document_receiveUpload:
    pattern:  /receiveUpload
    defaults: { _controller: 'MesdFileDocumentBundle:Document:receiveUpload' }
    requirements: { _method: post }

document_download:
    pattern:  /{id}/download
    defaults: { _controller: 'MesdFileDocumentBundle:Document:download' }
    requirements:
        id: \d+